### ISSUE TITLE
Authenticate without password

### ISSUE THREAD

**Issue by kumy** [pinepain/ldap-auth-proxy#8] opened 2018-11-06 10:05 UTC
I've just installed `ldap-auth-proxy` in proxy mode, during my tests I've found that while authenticating, if I just give the login without entering a password, the authentication is validated :(

Am I missing something?

**Comment by pinepain** [comment] 2018-11-06 11:38
Hi, there was such bug/feature during early development stage, afair, however it supposed to be fixed now. Can you please clarify what was your steps to set up the proxy?

**Comment by kumy** [comment] 2018-11-06 13:39
Please note, the example above use an Active Directory server.

I've setup the stack on another infrastructure, with an openldap backend, and I obtain `Failed to authenticate: LDAP Result Code 53 \"Unwilling To Perform\": unauthenticated bind (DN with no password) disallowed`. But this is a response from the openldap backend, not `ldap-auth-proxy`.

**Comment by pinepain** [comment] 2018-11-06 14:15
Thanks a lot for extra detauls, it's definitely weird and it's not something that is expected. Does AD allow user to have empty password, by chance? I know it sounds ridiculous but just to double check (have no AD here, unfortunately). I will double-check the code later today and will give it a try with OpenLDAP too. FTR, I use JumpCloud atm so example configs and all tests was done using their endpoint (I'm not affiliated with them though). For now I think it may be a good idea to reject immediately any credentials with empty username or password, in the end, it shouldn't work at LDAP anyway.

**Comment by kumy** [comment] 2018-11-06 14:18
Thanks for taking time to look into this.

> Does AD allow user to have empty password

It may, but my account has a password of course... I've tested with a few other apps, and the authentication is rejected when password is not given.

**Comment by pinepain** [comment] 2018-11-06 14:20
Can you please also post debug logs from both `ldap-auth-proxy` as well from traefik (I see that you use traefik in front of services, right?) and relevant web server config (at least the part that proxies auth to ldap-auth-proxy)?

**Comment by kumy** [comment] 2018-11-06 14:46
Here are the requested logs 
[ldap-auth-proxy.log](https://github.com/pinepain/ldap-auth-proxy/files/2553589/ldap-auth-proxy.log)
[traefik.log](https://github.com/pinepain/ldap-auth-proxy/files/2553619/traefik.log)

Regarding webserver, I didn't add specific config, just used `ldap-auth-proxy` as proxy like https://github.com/pinepain/ldap-auth-proxy#proxy

**Comment by pinepain** [comment] 2018-11-06 19:13
@microsoft This is why I do not bother supporting your products - 
![screen shot 2018-11-06 at 9 11 56 pm](https://user-images.githubusercontent.com/2185793/48087698-aa534600-e208-11e8-80e4-f5df5dba868a.png)

**Comment by kumy** [comment] 2018-11-06 19:35
@pinepain does this message come from Github???

**Comment by pinepain** [comment] 2018-11-06 19:40
Nope, I tried to register Azure account to be able to reproduce the issue you are having and apparently, if a user reside in Ukraine, they have to print, sign and send that agreement to Ireland. I'm just curious why printing and not writing it by hand? But never mind, I think the chance MS read and do sth is close to zero (from the negative side).

**Comment by pinepain** [comment] 2018-11-06 20:07
@kumy am I right that with openldap you are unable to authenticate with empty password and it's only possible with AD, is it correct?

**Comment by kumy** [comment] 2018-11-06 20:08
Exact, but I think the restriction in openldap can be adjusted via config.

**Comment by pinepain** [comment] 2018-11-06 20:17
@kumy hm, I double-checked `ldap-auth-proxy` code as well as [jtblin/go-ldap-client](https://github.com/jtblin/go-ldap-client) which is used under the hood and i think it's LDAP server-specific configuration, here's a similar issue discussed - https://github.com/Pylons/pyramid_ldap/issues/9#issuecomment-20543667. For now I'll make zero-length username or password to trigger auth failure immediately without contacting LDAP server, I see no good fit for empty usernameo password in in real world.

**Comment by pinepain** [comment] 2018-11-06 20:20
Here is another issue/report - https://github.com/go-ldap/ldap/issues/93 (just linking for the reference purpose).

**Comment by kumy** [comment] 2018-11-06 20:30
> For now I'll make zero-length username or password to trigger auth failure immediately without contacting LDAP server

I also feel this may be a nice default. For the general use, may it be switchable via a config option?

**Comment by pinepain** [comment] 2018-11-06 20:38
@kumy as per LDAP rfc, it may be, however in real life the reason people are putting auth is to avoid anonymous access and both anonymous and unauthenticated authentications do quite the opposite, so I see little or no this use case to applicable to the real world.

**Closed** 2018-11-06 20:55 UTC

**Comment by pinepain** [comment] 2018-11-06 21:11
@kumy could you please give `0.1.0` docker image tag a try?

**Comment by kumy** [comment] 2018-11-06 21:14
Sure, but have to wait tomorrow :disappointed: And thanks @pinepain for the quick fix!

**Comment by kumy** [comment] 2018-11-07 09:43
@pinepain just tested. I can see the rejection in the logs, so basically it works. However, we get an http 400 response code. Would be better to send back a 401, so users are requested to fill credentials again. Actually the session is "stalled", we have to clear the browser cache to have the opportunity to authenticate again.

**Comment by pinepain** [comment] 2018-11-07 13:17
Indeed, makes sense to me, pushed a fix and tagged as 0.1.1, thanks for the feedback.
